version: "3.2"
services:
  apollo:
    image: stackrox/apollo:${APOLLO_IMAGE_TAG:-latest}
    networks:
      net:
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
  apollo-ui:
    image: stackrox/apollo:ui-${APOLLO_IMAGE_TAG:-latest}
    networks:
      net:
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
  agent:
    image: stackrox/apollo:${APOLLO_IMAGE_TAG:-latest}
    entrypoint:
      - swarm-agent
    depends_on:
      - apollo
    networks:
      net:
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role==manager
    environment:
      - "ROX_APOLLO_ENDPOINT=apollo.apollo_net:8080"
      - "ROX_APOLLO_CLUSTER_ID=test"
      - "ROX_APOLLO_ADVERTISED_ENDPOINT=agent.apollo_net:8080"
      - "ROX_APOLLO_IMAGE=stackrox/apollo:${APOLLO_IMAGE_TAG:-latest}"
networks:
  net:
    driver: overlay
    attachable: true
