version: "3.2"
services:
  apollo:
    image: stackrox/apollo:latest
    networks:
      net:
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
  agent:
    image: stackrox/apollo:latest
    entrypoint:
      - swarm-agent
    depends_on:
      - apollo
    networks:
      net:
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role==manager
    environment:
      - "APOLLO_ENDPOINT=apollo.apollo_net:8080"
networks:
  net:
    driver: overlay
    attachable: true
