# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = ["bitbucket.org/stack-rox/apollo","github.com/docker/docker/daemon"]

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "7c9e64a2e1891bf1020d9312a18741c734fa1cd6"
  [metadata]
  upstream = "17.09-ce plus additional commits to fix Darwin build"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "e6516b3d5dc780cb57a976013c242a9a93052543"

[[constraint]]
  name = "github.com/docker/go-units"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "=1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  branch = "master"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  branch = "master"

[[constraint]]
  name = "github.com/heroku/docker-registry-client"
  source = "git@bitbucket.org:stack-rox/docker-registry-client.git"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "v1.7"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "v1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "a3f3340b5840cee44f372bddb5880fcbc419b46a"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  branch = "master"

[[override]]
  name = "github.com/google/certificate-transparency-go"
  branch = "master"

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  version = "2.1.3"
  name = "gopkg.in/square/go-jose.v2"

[[constraint]]
  name = "github.com/coreos/clair"
  version = "v2.0.1"
