# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = ["bitbucket.org/stack-rox/apollo","github.com/docker/docker/daemon"]

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "7c9e64a2e1891bf1020d9312a18741c734fa1cd6"
  [metadata]
  upstream = "17.09-ce plus additional commits to fix Darwin build"

[[constraint]]
  name = "github.com/docker/go-units"
  revision = "0dadbb0345b35ec7ef35e228dabb8de89a65bf52"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "130e6b02ab059e7b717a096f397c5b60111cae74"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  revision = "6d3547c644afb325c16df96e3c7177ea6e2fdebd"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "c323909dd41de182a54b4d1610f26034da5e097e"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  revision = "0a025b7e63adc15a622f29b0b2c4c3848243bbf6"

[[constraint]]
  name = "github.com/heroku/docker-registry-client"
  revision = "fd2fe803496897db70c236ee244f41487ea92ec2"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "e6516b3d5dc780cb57a976013c242a9a93052543"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "5bf94b69c6b68ee1b541973bb8e1144db23a194b"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "golang.org/x/net"
  revision = "dc871a5d77e227f5bbf6545176ef3eeebf87e76e"

[[constraint]]
  name = "google.golang.org/genproto"
  revision = "f676e0f3ac6395ff1a529ae59a6670878a8371a6"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "85ace5365f33b16fc735c866a12e3c765b9700f2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "3.0.0"
