apiVersion: v1
kind: Service
metadata:
  name: apollo
  namespace: stackrox
spec:
  ports:
  - name: api
    port: 443
    targetPort: 443
  selector:
    app: apollo
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apollo
  namespace: stackrox
  labels:
    app: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      namespace: stackrox
      labels:
        app: apollo
    spec:
      containers:
      - image: stackrox/apollo:latest
        imagePullPolicy: Always
        name: apollo
        ports:
        - name: api
          containerPort: 443
        env:
        - name: ROX_FEATURE_MTLS
          value: "false"
      imagePullSecrets:
      - name: stackrox
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: agent
  namespace: stackrox
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      namespace: stackrox
      labels:
        app: agent
    spec:
      containers:
      - image: stackrox/apollo:latest
        env:
        - name: ROX_FEATURE_MTLS
          value: "false"
        - name: ROX_APOLLO_ENDPOINT
          value: apollo.stackrox:443
        - name: ROX_APOLLO_CLUSTER_ID
          value: test
        - name: ROX_APOLLO_IMAGE
          value: stackrox/apollo:latest
        - name: ROX_APOLLO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROX_APOLLO_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        imagePullPolicy: Always
        name: agent
        command:
          - kubernetes-agent
      imagePullSecrets:
      - name: stackrox
