version: 2
jobs:
  build:
    docker:
      # This image is the standard circleci/golang:1.9.2 image, plus bazel
      # and other necessary build tools like goimports, dep, and yarn.
      - image: stackrox/apollo:circleci@sha256:d10504619e1b9ea218c5a8f02968f38d0ee7d04d0764fcf35e4d75729eafaad9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: /go/src/bitbucket.org/stack-rox/apollo
    steps:
      - checkout
      - setup_remote_docker

      - run: make -C apollo-ui

      - run: docker tag stackrox/apollo:ui-latest stackrox/apollo:ui-$CIRCLE_SHA1
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push stackrox/apollo:ui-$CIRCLE_SHA1

      - run: make all

      - run: docker tag stackrox/apollo:latest stackrox/apollo:$CIRCLE_SHA1
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push stackrox/apollo:$CIRCLE_SHA1

  retag:
    docker:
      - image: circleci/golang:1.9.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker

      - run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker pull stackrox/apollo:$CIRCLE_SHA1
          docker tag stackrox/apollo:$CIRCLE_SHA1 stackrox/apollo:latest
          docker push stackrox/apollo:latest
          docker pull stackrox/apollo:ui-$CIRCLE_SHA1
          docker tag stackrox/apollo:ui-$CIRCLE_SHA1 stackrox/apollo:ui-latest
          docker push stackrox/apollo:ui-latest

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - retag:
          requires:
            - build
          filters:
            branches:
              only:
                - master
