version: 2
jobs:
  build:
    docker:
      # This image is the standard circleci/golang:1.9.2 image, plus bazel
      # and other necessary build tools like goimports, dep, yarn, and envsubst.
      - image: stackrox/apollo:circleci@sha256:0c34ed2da594f58d50159ddd3f5453f0d5768c428d658af37ce901fabf5c1b08
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: /go/src/bitbucket.org/stack-rox/apollo
    steps:
      - checkout
      - setup_remote_docker

      # Refresh the base image.
      - run: docker pull alpine:3.7

      # Build.
      - run: cat tools/ci-bazel.rc | envsubst > tools/bazel.rc
      - run: make all

      # Push.
      - run: docker tag stackrox/mitigate:latest stackrox/mitigate:$CIRCLE_SHA1
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push stackrox/mitigate:$CIRCLE_SHA1

  retag:
    docker:
      - image: circleci/golang:1.9.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker

      - run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker pull stackrox/mitigate:$CIRCLE_SHA1
          docker tag stackrox/mitigate:$CIRCLE_SHA1 stackrox/mitigate:latest
          docker push stackrox/mitigate:latest

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - retag:
          requires:
            - build
          filters:
            branches:
              only:
                - master
