# permissions for end users to edit securedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securedcluster-editor-role
rules:
- apiGroups:
  - platform.stackrox.io
  resources:
  - securedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.stackrox.io
  resources:
  - securedclusters/status
  verbs:
  - get
