version: "3.2"
services:
  central:
    image: stackrox/mitigate:${MITIGATE_IMAGE_TAG:-latest}
    networks:
      net:
    ports:
      - target: 443
        published: 8080
        protocol: tcp
        mode: ingress
    secrets:
      - source: mitigate_private_key
        target: stackrox.io/ca-key.pem
        mode: 400
      - source: mitigate_certificate
        target: stackrox.io/ca.pem
        mode: 400
networks:
  net:
    driver: overlay
    attachable: true
secrets:
  mitigate_private_key:
    file: ./ca-key.pem
  mitigate_certificate:
    file: ./ca.pem
