apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rhacs-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: rhacs-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
