version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/ui"
    update_schedule: "monthly"
    default_reviewers:
      - "stackrox/ui-dep-reviewers"
    default_labels:
      - "ci-no-api-tests"
      - "ci-no-qa-tests"
      - "ci-no-upgrade-tests"
      - "dependencies"
  - package_manager: "java:gradle"
    directory: "/qa-tests-backend"
    update_schedule: "monthly"
    default_reviewers:
      - "stackrox/backend-dep-reviewers"
    default_labels:
      - "ci-no-api-tests"
      - "ci-no-ui-tests"
      - "dependencies"
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "monthly"
    default_reviewers:
      - "stackrox/backend-dep-reviewers"
    default_labels:
      - "dependencies"
