kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: monitor-deployments
rules:
  - resources:
    - daemonsets
    - deployments
    - deploymentconfigs
    - pods
    - replicasets
    - replicationcontrollers
    - services
    - statefulsets
    apiGroups:
    - '*'
    verbs:
    - get
    - watch
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: monitor-deployments-binding
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: monitor-deployments
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: enforce-policies
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: launch-benchmarks
rules:
  - resources:
    - daemonsets
    apiGroups:
    - extensions
    verbs:
    - create
    - get
    - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: launch-benchmarks-binding
  namespace: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: Role
  name: launch-benchmarks
  apiGroup: rbac.authorization.k8s.io
