apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./tests/central
- ./tests/securedcluster
# central pod takes a while do become healthy, typically ~25s, but sometimes over a minute since container start.
# We need to add CR reconciliation, pod creation and image fetch to that.
# Set the timeout very high so that we can collect a distribution of realistic times and later set to a flake-safe timeout.
timeout: 300
reportFormat: xml
artifactsDir: build/kuttl-test-artifacts
commands:
- command: env NO_PROXY=127.1.2.3/8 ./bin/manager  # use a test value for NO_PROXY. This will not have any impact
                                                   # on the services at runtime, but we can test if it gets piped
                                                   # through correctly.
  background: true
