apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./tests/central
commands:
- command: make run
  background: true
# The following commands are only necessary because we only support a fixed namespace name, which in turn requires
# kuttl --namespace flag, and this in turn requires namespace to be in place before we start testing.
# If/when we support arbitrary namespaces, then we can drop --namespace and the following commands,
# and kuttl will create and clean up ephemeral namespaces for us, with the additional ability to run tests in parallel.
# This first command is a no-op if namespace already exists, but ensures that the second command (delete) does not fail.
- command: kubectl apply -f tests/stackrox_namespaces.yaml
# This is needed to clean up stale resources (PVC, etc) from previous tests, if any.
- command: kubectl delete -f tests/stackrox_namespaces.yaml
# Namespace needs to exist to use kuttl with --namespace
- command: kubectl apply -f tests/stackrox_namespaces.yaml
